### ISSUE TITLE
Develop File Listing Interface with React

### ISSUE THREAD

**Issue by alefmanvladimir** [alefmanvladimir/BigFiles#1]
**Description:** Implement a clear and user-friendly interface in React to display a list of uploaded files within the TON Drive application. Users should be able to easily navigate, search, and manage their files.

**Additional Notes:**

- Incorporate features like sorting (by name, date, size) and searching for efficient file management.

- Ensure compatibility with various file types, showcasing appropriate icons or previews.

- Leverage popular React libraries and components for enhanced UX and performance.

- Implement stub, which simulates fetching data from the data source.

**Comment by d0rich** [comment]
I'd like to take this one
