### ISSUE TITLE
Develop Project Architecture for TON Drive

### ISSUE THREAD

**Issue by alefmanvladimir** [alefmanvladimir/BigFiles#2]
**Description:** Define and structure the architecture for the TON Drive application. The architecture should ensure scalability, security, and efficient interaction between frontend and backend components.

**Additional Notes:**

- Ensure that the architecture accommodates TON Storage integration seamlessly.
- Document the chosen architecture in an architecture.md file within the project repository. Use diagrams and descriptions to aid other contributors in understanding the system layout. Include links to external tools like draw.io where relevant diagrams are hosted.

**Comment by vidhan63-soe** [comment]
Hello @alefmanvladimir ,
can u explain about task little more, I don't get what exactly to do?

**Comment by alefmanvladimir** [comment]
@vidhan63-soe  Hello, you are welcome to join this [chat ](https://t.me/tondrive1) to discuss the project
