### ISSUE TITLE
Develop File Upload Interface with React

### ISSUE THREAD

**Issue by alefmanvladimir** [alefmanvladimir/BigFiles#4]
**Description:** Create a straightforward and intuitive file upload interface using React for users to add their files to the TON Drive. This should include options to select, drag-and-drop files, and monitor upload progress.

**Additional Notes:**

- The interface should provide feedback on successful uploads and errors.

- Consider using React libraries for drag-and-drop functionality.

- Features like batch upload or pausing/resuming uploads would enhance user experience.

**Comment by nitinryali** [comment]
Please assign this to me

**Comment by d0rich** [comment]
It looks like this task also requires some backend, which accepts the file.

@alefmanvladimir @nitinryali should we include backend part into this task or create new one? Maybe it will be difficult for one person.
