### ISSUE TITLE
Deploy TON Storage Daemon on Cluster

### ISSUE THREAD

**Issue by alefmanvladimir** [alefmanvladimir/BigFiles#5]
**Description:** Set up and deploy the TON Storage Daemon on our cluster to ensure the TON Drive application can interact seamlessly with TON Storage. This is a crucial step for facilitating large file storage and transfer capabilities.

**Additional Notes:**

- Document the deployment process, configurations, and any challenges faced in a deployment.md file within the project repository.

- Test connectivity from the TON Drive application to the daemon once deployed, ensuring smooth integration.

**Comment by d0rich** [comment]
@alefmanvladimir Do you have any details regarding this cluster? Maybe some link by provider?
